LINKEDIN_COMPANIES_FIELDS_MAPPING = {
    'name': 'name',
    'logo': 'logo',
    "banner": "banner",
    "description": "description",
    "followerCount": "followerCount",
    "website": "website",
    "domain": "domain",
    "location": "location",
    "companyAddress": "companyAddress",
    "industry": "industry",
    "companySize": "companySize",
    "headquarters": "headquarters",
    "founded": "founded",
    "mainCompanyID": "mainCompanyID",
    "linkedinID": "linkedinID",
    "salesNavigatorLink": "salesNavigatorLink",
    "employeesOnLinkedIn": "employeesOnLinkedIn",
    "companyName": "companyName",
    "query": "url",
    "timestamp": "timestamp",
    "totalEmployeeCount": "totalEmployeeCount",
    "growth6Mth": "growth6Mth",
    "growth1Yr": "growth1Yr",
    "growth2Yr": "growth2Yr",
    "averageTenure": "averageTenure",
    "distributionInformationTechnology": "distributionInformationTechnology",
    "distributionResearch": "distributionResearch",
    "distributionFinance": "distributionFinance",
    "distributionMediaAndCommunication": "distributionMediaAndCommunication",
    "distributionEngineering": "distributionEngineering",
    "distributionBusinessDevelopment": "distributionBusinessDevelopment",
    "distributionOperations": "distributionOperations",
    "distributionAdministrative": "distributionAdministrative",
    "distributionProgramAndProjectManagement": "distributionProgramAndProjectManagement",
    "distributionConsulting": "distributionConsulting",
    "distributionHumanResources": "distributionHumanResources",
}

LINKEDIN_COMPANY_EMPLOYEES_FIELDS_MAPPING = {
    'profileUrl': 'profileUrl',
    'firstName': 'firstName',
    "lastName": "lastName",
    "job": "job",
    "location": "location",
}